name: Deployment Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: cd-${{ github.ref }}
  cancel-in-progress: true 

jobs:

    Deploy:
        name: bundle deploy to all targets
        runs-on: ubuntu-latest
        environment: platform-approval

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install Databricks CLI
              uses: databricks/setup-cli@main

            - name: Bundle deploy to dev
              run: databricks bundle deploy --target dev
              env:                                         # SP credentials from GitHub Secrets
                DATABRICKS_AUTH_TYPE: azure-client-secret
                DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST_DEV }}
                ARM_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
                ARM_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET }}
                ARM_TENANT_ID: ${{ secrets.DATABRICKS_AZURE_TENANT_ID }}

            - name: Bundle deploy to qa
              run: databricks bundle deploy --target qa
              env:                                         # SP credentials from GitHub Secrets
                DATABRICKS_AUTH_TYPE: azure-client-secret
                DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST_QA }}
                ARM_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
                ARM_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET }}
                ARM_TENANT_ID: ${{ secrets.DATABRICKS_AZURE_TENANT_ID }}
            
            - name: Bundle deploy to prod
              run: databricks bundle deploy --target prod
              env:                                         # SP credentials from GitHub Secrets
                DATABRICKS_AUTH_TYPE: azure-client-secret
                DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST_PROD }}
                ARM_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
                ARM_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET }}
                ARM_TENANT_ID: ${{ secrets.DATABRICKS_AZURE_TENANT_ID }}