targets:

  prod:

    variables:
      deployer_sp: "prod-application-deployer-sp"

    workspace: 
      host: https://adb-7405617227505068.8.azuredatabricks.net/
      
    permissions:
      - group_name: Data Engineers
        level: CAN_VIEW